version: '3'
services:
  map_builder:
    image: map_builder
    build: .
    environment:
      - city=$city
      - bbox=$bbox
    volumes:
      - ../out:/app/out
    depends_on:
      tileserver:
        condition: service_healthy

  tileserver:
    image: maptiler/tileserver-gl
    command: --config /data/config.json --verbose
    volumes:
      - ./data:/data
    # ports:
    #   - 8087:8080
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 30s
      timeout: 15s
      retries: 3